

safe_int_test.x : safe_int.h safe_int_test.cpp
	g++ -o safe_int_test.x  safe_int_test.cpp -lboost_unit_test_framework


lut_test.x : lut.h lut_test.cpp
	g++ -o lut_test.x lut_test.cpp -std=c++0x -Wall -pedantic
