
# unit_expr_parser_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '-v\x1c\xe7\xc6\xf5\x93\x0e\x9d4\xc05\xd4\x07\xc1\xd0'
    
_lr_action_items = {'ALPHATOKEN':([0,4,6,8,10,15,19,21,22,27,29,],[5,5,5,5,5,5,5,5,5,5,5,]),'WHITESPACE':([0,2,3,4,5,6,8,9,10,13,14,15,16,17,19,20,21,22,25,26,27,28,29,30,31,32,33,35,36,],[4,-16,14,4,-22,4,19,21,4,-20,-15,27,14,21,19,21,-18,4,-21,14,27,21,19,-12,-17,14,21,21,-13,]),'FLOAT':([0,24,],[6,6,]),'LBRACKET':([0,4,6,10,15,22,27,],[8,8,8,8,8,8,8,]),'SLASH':([2,3,5,9,11,13,14,16,17,18,20,21,23,25,26,28,30,31,32,33,36,],[-16,15,-22,22,24,-20,-15,-14,-19,-5,29,-18,-6,-21,-9,-11,-12,-17,-10,-8,-13,]),'INTEGER':([0,5,13,24,],[10,-22,25,10,]),'RBRACKET':([2,5,13,17,20,21,25,31,35,],[-16,-22,-20,-19,30,-18,-21,-17,36,]),'$end':([1,2,5,7,9,11,12,13,14,16,17,18,21,23,25,26,28,30,31,32,33,34,36,],[-1,-16,-22,-2,-7,-3,0,-20,-15,-14,-19,-5,-18,-6,-21,-9,-11,-12,-17,-10,-8,-4,-13,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'unit_expr':([0,6,10,],[1,18,23,]),'unit_term':([0,4,6,8,10,15,19,21,22,27,29,],[2,2,2,2,2,2,2,31,2,2,2,]),'parameterised_unit_term':([0,4,6,10,15,22,27,],[3,16,3,3,26,32,16,]),'quantity_expr':([0,],[7,]),'unit_term_grp':([0,4,6,8,10,15,19,22,27,29,],[9,17,9,20,9,28,17,33,17,35,]),'quantity_term':([0,24,],[11,34,]),'unit_term_unpowered':([0,4,6,8,10,15,19,21,22,27,29,],[13,13,13,13,13,13,13,13,13,13,13,]),'gen_expr':([0,],[12,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> gen_expr","S'",1,None,None,None),
  ('gen_expr -> unit_expr','gen_expr',1,'p_gen_expr','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',10),
  ('gen_expr -> quantity_expr','gen_expr',1,'p_gen_expr','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',11),
  ('quantity_expr -> quantity_term','quantity_expr',1,'p_quantity_expr_1','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',18),
  ('quantity_expr -> quantity_term SLASH quantity_term','quantity_expr',3,'p_quantity_expr_2','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',22),
  ('quantity_term -> FLOAT unit_expr','quantity_term',2,'p_quantity_term_1','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',28),
  ('quantity_term -> INTEGER unit_expr','quantity_term',2,'p_quantity_term_1','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',29),
  ('unit_expr -> unit_term_grp','unit_expr',1,'p_unit_expr_1','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',36),
  ('unit_expr -> unit_term_grp SLASH unit_term_grp','unit_expr',3,'p_unit_expr_2','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',40),
  ('unit_expr -> parameterised_unit_term SLASH parameterised_unit_term','unit_expr',3,'p_unit_expr_3','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',44),
  ('unit_expr -> unit_term_grp SLASH parameterised_unit_term','unit_expr',3,'p_unit_expr_4','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',48),
  ('unit_expr -> parameterised_unit_term SLASH unit_term_grp','unit_expr',3,'p_unit_expr_5','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',52),
  ('parameterised_unit_term -> LBRACKET unit_term_grp RBRACKET','parameterised_unit_term',3,'p_paramterised_unit_term_1','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',60),
  ('parameterised_unit_term -> LBRACKET unit_term_grp SLASH unit_term_grp RBRACKET','parameterised_unit_term',5,'p_paramterised_unit_term_2','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',64),
  ('parameterised_unit_term -> WHITESPACE parameterised_unit_term','parameterised_unit_term',2,'p_paramterised_unit_term_3','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',69),
  ('parameterised_unit_term -> parameterised_unit_term WHITESPACE','parameterised_unit_term',2,'p_paramterised_unit_term_4','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',74),
  ('unit_term_grp -> unit_term','unit_term_grp',1,'p_unit_term_grp_1','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',82),
  ('unit_term_grp -> unit_term_grp WHITESPACE unit_term','unit_term_grp',3,'p_unit_term_grp_2','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',86),
  ('unit_term_grp -> unit_term_grp WHITESPACE','unit_term_grp',2,'p_unit_term_grp_3','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',91),
  ('unit_term_grp -> WHITESPACE unit_term_grp','unit_term_grp',2,'p_unit_term_grp_4','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',95),
  ('unit_term -> unit_term_unpowered','unit_term',1,'p_unit_term_1','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',103),
  ('unit_term -> unit_term_unpowered INTEGER','unit_term',2,'p_unit_term_2','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',107),
  ('unit_term_unpowered -> ALPHATOKEN','unit_term_unpowered',1,'p_unit_term_unpowered_token','/home/michael/hw/NeuroUnits/src/python_ply/units_expr_yacc.py',115),
]
